"""
Merges multiple .tex files from the latex/ folder into latex/main.tex.

Edit PARTS to set the order of your files. Then either:
  - Upload the entire latex/ folder to Overleaf, or
  - cd into latex/ and run: pdflatex main.tex
"""
import os
from pathlib import Path
os.chdir(Path(__file__).resolve().parent.parent)

LATEX_DIR = "latex"

# ── Edit this list to set the order of your .tex parts ───────────────────────
PARTS = [
    # "introduction.tex",   # hand-written
    "results.tex",          # auto-generated by ais_project.py
    # "analysis.tex",       # hand-written
    # "conclusion.tex",     # hand-written
]

PREAMBLE = r"""\documentclass[12pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{amsmath}

\title{AIS Project}
\author{Ulisse Palmiero}
\date{April 2026}

\begin{document}
\maketitle

"""

output_path = os.path.join(LATEX_DIR, "main.tex")
with open(output_path, "w", encoding="utf-8") as out:
    out.write(PREAMBLE)
    for part in PARTS:
        full_path = os.path.join(LATEX_DIR, part)
        if os.path.exists(full_path):
            out.write(f"\\input{{{part}}}\n\n")
        else:
            print(f"Warning: {full_path} not found -- skipping")
    out.write("\\end{document}\n")

print(f"Created {output_path}")
print("Upload the latex/ folder to Overleaf, or cd into latex/ and run: pdflatex main.tex")
